// import { Montserrat } from 'next/font/google';
import cn from 'classnames';
import { cookies } from 'next/headers';
import { cookie } from '~/shared/lib';
import { Providers } from './_providers/Providers';
import '~/styles/globals.scss';

// const montserrat = Montserrat({
//     subsets: ['latin', 'cyrillic'],
//     variable: '--font-montserrat',
// });

export const metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default ({ children }: React.PropsWithChildren) => {
    return (
        <html data-theme={cookie(cookies).get('theme')}>
            <head />
            <body className={cn('bg-primary font-montserrat text-primary' /*, montserrat.variable */)}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
};
